import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
const { Client } = require("@notionhq/client");

export default function Home({ tasks }) {
  console.log(tasks);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js + Notion = Task App</h1>

        <div className={styles.grid}>
          {tasks.map((task) => (
            <div
              key={task.id}
              className={styles.card}
              style={{
                display: "flex",
                flexDirection: "row",
                alignItems: "center",
              }}
            >
              {/* <input
                type="checkbox"
                style={{ marginRight: "20px" }}
                checked={task.properties.Done.checkbox}
              /> */}
              <h2>{task.properties.Task.title[0].text.content}</h2>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const notion = new Client({ auth: process.env.NOTION_API_KEY });
  const databaseId = process.env.NOTION_DATABASE_ID;

  const response = await notion.databases.query({
    database_id: databaseId,
  });
  return {
    props: {
      tasks: response.results,
    },
    revalidate: 1,
  };
}
